# exercise 5 and 6 left. [DONE]

name = PropertiesConfig
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%5p] %d{EEE, yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} in [%M] at line %L: %msg%n

appender.file.type = File
appender.file.name = logFile
appender.file.fileName = logs/app.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = [%5p] %d{EEE, yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} in [%M] at line %L: %msg%n
appender.file.append = true

rootLogger.level = debug
rootLogger.appenderRef.stderr.ref = consoleLogger
rootLogger.appenderRef.file.ref = logFile
#rootLogger.appenderRef.stdout.ref = consoleLogger